---
language: python

python:
  - 3.7
env:
  global:
    CC_TEST_REPORTER_ID=$CODECLIMATE_REPORTER_ID

branches:
  only:
    - master

jobs:
  include:
    - stage: Base linting
      install: pip install flake8
      script: flake8 app.py

    - stage: CI - Test Codebase - Quality Gate
      before_script:
        -  curl -L  https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      install:
        - pip install --upgrade pip pipenv
        - pipenv install --system --deploy
      script:
        - pytest --cov=app
      after_script:
        - coverage xml
        - >
          if [[ "$TRAVIS_PULL_REQUEST" == "false" ]];
          then ./cc-test-reporter after-build
          --exit-code $TRAVIS_TEST_RESULT; fi

    - stage: CD - Deploy Database
      if: branch = master
      install:
        - pip install --upgrade pip pipenv
        - pipenv install --system --deploy
      script:
        - python app.py
        - gzip --verbose clean_data/base156.sqlite
      before_deploy:
        - pipenv lock -r --dev > requirements.txt
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=$(cat VERSION)-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
        - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
        - git push -q https://$TAGPERM@github.com/joepreludian/recrutatech_devops_ia --tags
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH
        file_glob: true
        file: clean_data/*
        skip_cleanup: true
        on:
          tags: true
